ALTER TABLE questions
ADD COLUMN code_snippet TEXT,
ADD COLUMN option1 VARCHAR(255) NOT NULL,
ADD COLUMN option2 VARCHAR(255) NOT NULL,
ADD COLUMN option3 VARCHAR(255) NOT NULL,
ADD COLUMN option4 VARCHAR(255) NOT NULL,
ADD COLUMN question_text TEXT NOT NULL,
ADD COLUMN correct_option INT NOT NULL,
ADD COLUMN subject_id BIGINT NOT NULL,
ADD COLUMN updated_at DATETIME(6) NOT NULL,
DROP COLUMN content,
DROP COLUMN option_a,
DROP COLUMN option_b,
DROP COLUMN option_c,
DROP COLUMN option_d,
DROP COLUMN correct_answer;

ALTER TABLE questions 
ADD CONSTRAINT FK_questions_subject FOREIGN KEY (subject_id) REFERENCES subjects(id);