ALTER TABLE questions 
ADD COLUMN IF NOT EXISTS code_snippet TEXT,
ADD COLUMN IF NOT EXISTS option1 VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS option2 VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS option3 VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS option4 VARCHAR(255) NOT NULL,
ADD COLUMN IF NOT EXISTS question_text TEXT NOT NULL,
ADD COLUMN IF NOT EXISTS correct_option INT NOT NULL,
ADD COLUMN IF NOT EXISTS subject_id BIGINT NOT NULL,
ADD COLUMN IF NOT EXISTS updated_at DATETIME(6) NOT NULL,
ADD COLUMN IF NOT EXISTS type ENUM('OBJECTIVE','DESCRIPTIVE') DEFAULT NULL,
DROP COLUMN IF EXISTS content,
DROP COLUMN IF EXISTS option_a,
DROP COLUMN IF EXISTS option_b,
DROP COLUMN IF EXISTS option_c,
DROP COLUMN IF EXISTS option_d,
DROP COLUMN IF EXISTS correct_answer;

ALTER TABLE questions 
ADD CONSTRAINT FK_questions_subject FOREIGN KEY (subject_id) REFERENCES subjects(id);